name: Update Lottery

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:     # Allow manual run

permissions:
  contents: write        # Allow the action to push changes

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Lottery Script
        run: python scripts/update_lottery.py

      - name: Commit and Push Results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add lottery_status.json lottery_entries.json
          git commit -m "Auto-update lottery data"
          git push
