name: Update Lottery Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Manual trigger option

jobs:
  update-lottery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python (if needed)
        run: |
          python -m pip install --upgrade pip

      - name: Run Lottery Script
        run: python scripts/update_lottery_status.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "blockman-ai"
          git config --global user.email "bot@blockman.ai"
          git add lottery_entries.json lottery_status.json winners_history.json

          if ! git diff --cached --quiet; then
            git commit -m "Update lottery data automatically"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          else
            echo "No changes to commit."
