name: Update Lottery

on:
  schedule:
    - cron: "0 * * * *"  # Every hour
  workflow_dispatch:

permissions:
  contents: write  # Needed to allow push

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Entry Detection Script
        run: python scripts/update_lottery.py

      - name: Commit and Push Updates
        run: |
          git config --global user.name "blockman-ai"
          git config --global user.email "bot@blockman.ai"
          git add lottery_entries.json lottery_status.json
          git commit -m "Update lottery entries"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
